#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# autoload -Uz promptinit
# promptinit
# prompt peepcode ☢

MYSQL=/usr/local/mysql/bin
export PATH=$PATH:$MYSQL
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
# export PATH='/usr/local/sbin:$PATH'
# for tmux: export 256color
export TERM=xterm-256color
export DIBS_LOCAL="$HOME/Projects/Nike/RSVP/dw-dibs"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH="/usr/local/opt/postgresql@13/bin:$PATH"
export PATH=/opt/homebrew/bin:$PATH

# Make ls directory names readable on black background
export LSCOLORS=ExfxcxdxbxEgEdabagacad

#ALIASES

# Run Rubocop on your changed files
alias rubo="git diff --name-only --diff-filter=MA | xargs rubocop"

# Docker Aliases
alias dc="docker-compose"

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# List all files colorized in long format, including dot files
alias ll="ls -Gla"

# Shortcuts
alias g="git --no-pager"
alias v="nvim"
alias ls="ls -G"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias br="./bin/rails"
alias jg="grep -RIE --exclude-dir=node_modules --exclude-dir=public --exclude-dir=bootsnap --exclude-dir=coverage --exclude-dir=tinymce --exclude-dir=tmp --exclude-dir=vendor --exclude-dir=log --exclude-dir=bundler --exclude-dir=.git --devices=skip --exclude=\"*.js.map\" --exclude=\"*.svg\""

# File size
alias fs="stat -f \"%z bytes\""

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do alias "$method"="lwp-request -m '$method'"; done

eval "$(rbenv init -)"
export EDITOR='nvim'
export BUNDLER_EDITOR='nvim'
source ~/.tmuxinator.zsh
eval "$(direnv hook zsh)"

# Add fzf to your ctrl + r terminal reverse search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"


# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jswatosh/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
