#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# autoload -Uz promptinit
# promptinit
# prompt peepcode ☢

# for tmux: export 256color
export TERM=xterm-256color
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
export PATH=/opt/homebrew/bin:$PATH

# Make ls directory names readable on black background
export LSCOLORS=ExfxcxdxbxEgEdabagacad

#ALIASES

# Run Rubocop on your changed files
alias rubo="git diff --name-only --diff-filter=MA | xargs bundle exec rubocop"

# Docker Aliases
alias dc="docker-compose"

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# List all files colorized in long format, including dot files
alias ll="ls -Gla"

# Shortcuts
alias g="git --no-pager"
alias v="nvim"
alias ls="ls -G"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias be="bundle exec"

alias jg="grep -RIE --exclude-dir=.ruby-lsp --exclude-dir=node_modules --exclude-dir=public --exclude-dir=bootsnap --exclude-dir=coverage --exclude-dir=tinymce --exclude-dir=tmp --exclude-dir=vendor --exclude-dir=log --exclude-dir=bundler --exclude-dir=.git --devices=skip --exclude=\"*.js.map\" --exclude=\"*.svg\""

alias all-repos-pull="find ~ \( -path ~/Library/* -or -path ~/.Trash* -or -path ~/.local/* \) -prune -or -maxdepth 6 -type d -name .git -print -execdir zsh -c 'git remote -v show | tee >([ \$(wc -c) -gt 0 ] && git pull --all --prune || pwd) &' \;"

alias all-repos-status="find ~ \( -path ~/Library/* -or -path ~/.Trash* -or -path ~/.local/* \) -prune -or -maxdepth 6 -type d -name .git -exec sh -c 'for d in \$(dirname \$@) ; do ( cd "\$d" || exit ; printf \"#%.0s\" {1..88} ; printf \"\n\" ; pwd ; git status -sb ) ; done' _ {} \;"

# File size
alias fs="stat -f \"%z bytes\""

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do alias "$method"="lwp-request -m '$method'"; done

eval "$(rbenv init -)"

export EDITOR='nvim'
export BUNDLER_EDITOR='nvim'
export MANPAGER='/opt/homebrew/bin/nvim +Man!'

source ~/.tmuxinator.zsh
eval "$(direnv hook zsh)"

# Add fzf to your ctrl + r terminal reverse search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
export PATH="/opt/homebrew/opt/libpq/bin:$PATH"


# The following lines have been added by Docker Desktop to enable Docker CLI completions.
fpath=(/Users/jswatosh/.docker/completions $fpath)
autoload -Uz compinit
compinit
# End of Docker CLI completions
