#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.

if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# autoload -Uz promptinit
# promptinit
# prompt peepcode ☢

MYSQL=/usr/local/mysql/bin
export PATH=$PATH:$MYSQL
export DYLD_LIBRARY_PATH=/usr/local/mysql/lib:$DYLD_LIBRARY_PATH
# export PATH='/usr/local/sbin:$PATH'
# for tmux: export 256color
export TERM=xterm-256color
export DIBS_LOCAL="$HOME/Projects/Nike/RSVP/dw-dibs"
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig"
export PATH=$HOME/.composer/vendor/bin:$PATH
export PATH="/usr/local/opt/postgresql@13/bin:$PATH"
export PATH=/opt/homebrew/bin:$PATH

#ALIASES

alias trun='bundle exec torquebox run -J "\-Xmx2048m"'

# Run Rubocop on your changed files
alias rubo="git diff --name-only --diff-filter=MA | xargs rubocop"

# Docker Aliases
alias dc="docker-compose"
alias dcra="docker-compose run app"

# Easier navigation: .., ..., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ~="cd ~" # `cd` is probably faster to type though
alias -- -="cd -"

# List all files colorized in long format, including dot files
alias ll="ls -Gla"

# List only directories
alias lsd='ls -l | grep "^d"'

# Undo a `git push`
alias undopush="git push -f origin HEAD^:master"

# IP addresses
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias localip="ipconfig getifaddr en1"
alias ips="ifconfig -a | perl -nle'/(\d+\.\d+\.\d+\.\d+)/ && print $1'"

# Flush Directory Service cache
alias flush="dscacheutil -flushcache"

# View HTTP traffic
alias sniff="sudo ngrep -d 'en1' -t '^(GET|POST) ' 'tcp and port 80'"
alias httpdump="sudo tcpdump -i en1 -n -s 0 -w - | grep -a -o -E \"Host\: .*|GET \/.*\""

# Start an HTTP server from a directory
alias server="open http://localhost:8080/ && python -m SimpleHTTPServer 8080"

# Trim new lines and copy to clipboard
alias c="tr -d '\n' | pbcopy"

# Shortcuts
alias d="cd ~/Documents/Dropbox"
alias p="cd ~/Projects"
alias g="git"
alias gco='git co'
alias gci='git ci'
alias grb='git rb'
alias gps='git ps'
alias ga.='git add -A'
alias v="vim"
#alias vim="/usr/local/Cellar/macvim/9.4-77/MacVim.app/Contents/MacOS/Vim"
alias mysql="/usr/local/mysql/bin/mysql"
alias ls="ls -G"
alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false"
alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true"
alias pgstart="pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start"
alias pgstop="pg_ctl -D /usr/local/var/postgres stop -s -m fast"
alias gpsh="git push heroku master"
alias tree="find . -print | sed -e 's;[^/]*/;|____;g;s;____|; |;g'"
alias stage="gps;git push stage stage:master"
alias be='bundle exec'
alias isim="pen /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Applications/iPhone\ Simulator.app"
alias br="./bin/rails"

#Compile Rails Assets
alias precompile='RAILS_ENV=production bundle exec rake assets:precompile'

# Start coffee server or application.js
alias watchassets="~/sassycoffee.sh"

#watch coffee scripts
alias coffeewatch="coffee -o public/javascripts/ -cw app/assets/javascripts/"

#watch compass scripts
alias compasswatch="compass watch"

# Start redis
alias redis="redis-server /usr/local/etc/redis.conf"

# File size
alias fs="stat -f \"%z bytes\""

# ROT13-encode text. Works for decoding, too! ;)
alias rot13='tr a-zA-Z n-za-mN-ZA-M'

# Disable Spotlight
alias spotoff="sudo mdutil -a -i off"
# Enable Spotlight
alias spoton="sudo mdutil -a -i on"

# One of @janmoesen’s ProTip™s
for method in GET HEAD POST PUT DELETE TRACE OPTIONS; do alias "$method"="lwp-request -m '$method'"; done

# Stuff I never really use but cannot delete either because of http://xkcd.com/530/
alias stfu="osascript -e 'set volume output muted true'"
alias pumpitup="osascript -e 'set volume 10'"
alias hax="growlnotify -a 'Activity Monitor' 'System error' -m 'WTF R U DOIN'"

eval "$(rbenv init -)"
export EDITOR='vim'
source ~/.tmuxinator.zsh
eval "$(direnv hook zsh)"

# Add fzf to your ctrl + r terminal reverse search
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"  # This loads nvm
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"  # This loads nvm bash_completion
